### ISSUE TITLE
Error when starting version 1.7.1-6-open on a mongo 4.4 version

### ISSUE THREAD

**Issue by ncstc1** [pryv/open-pryv.io#17]
The error (warning?) message is:
```
2022-09-21 13:24:44 [error]: [api-server:Application:error-middleware]: Unhandled API error (MongoError): Invalid command argument. Expected '4.4' or '4.2', found 4.0 in: { setFeatureCompatibilityVersion: "4.0", lsid: { id: UUID("209d35ce-6032-4158-99b9-0620426af71f") }, $db: "admin" }. See https://docs.mongodb.com/master/release-notes/4.4-compatibility/#feature-compatibility.
MongoError: Invalid command argument. Expected '4.4' or '4.2', found 4.0 in: { setFeatureCompatibilityVersion: "4.0", lsid: { id: UUID("209d35ce-6032-4158-99b9-0620426af71f") }, $db: "admin" }. See https://docs.mongodb.com/master/release-notes/4.4-compatibility/#feature-compatibility.
    at MessageStream.messageHandler (/app/dist/node_modules/mongodb/lib/cmap/connection.js:299:20)
    at MessageStream.emit (node:events:390:28)
    at processIncomingData (/app/dist/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/app/dist/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at MessageStream.Writable.write (node:internal/streams/writable:334:10)
    at Socket.ondata (node:internal/streams/readable:754:22)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) 
}
```
The consequences are unclear though...

The error is there (this should probably not be hardcoded and go to the config, no?):
`components/storage/src/Database.js:152:      client.db('admin').command({ setFeatureCompatibilityVersion: "4.0" }, {}, callback);`

Cheers,
Stéphane.

**Comment by sgoumaz** [comment]
@ncstc1 Thanks for the notice (and your patience). The Mongo feature compatibility version will be set to 4.2 in the next version, so you'll be able to run Mongo 4.4.

(But I'm closing this as 'won't fix', as AFAIK Open-Pryv.io is only supposed to work with the provided Mongo version.)
